services:
  web:
    build: ./st_web
    ports:
      - "4321:80"
    volumes:
      - ./st_web:/app
    environment:
      TRANSLATOR_PROVIDER: google
      API_URL: "http://backend:8081"
      BACKEND_SERVER: "http://backend:8081"
      OLLAMA_SERVER: "http://ollama:11434"
      OPENAI_API_KEY: "sk-xxxxx"
      GROQ_API_KEY: "gsk-xxxxx"
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      HOST: "0.0.0.0"
      LLM_PROVIDER: groq
      LLM_MODEL: llama3-70b-8192
      LLM_API_TOKEN: "your-api-token-here"
      OLLAMA_SERVER: "http://ollama:11434"
      REDIS_SERVER: "db"
      REDIS_PORT: 6379
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data:/data
    networks:
      - mynet
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    networks:
      - mynet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./ollama:/root/.ollama:rw

networks:
  mynet:
    driver: bridge